In [ ]:
from sklearn.datasets import load_wine
import pandas as pd

data = load_wine()

X = pd.DataFrame(data.data, columns=data.feature_names)
y = pd.Series(data.target)

df = X.copy()
df["target"] = y

df.tail()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.7,0.64,1.74,740.0,2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.3,0.70,1.56,750.0,2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.2,0.59,1.56,835.0,2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.3,0.60,1.62,840.0,2
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.2,0.61,1.60,560.0,2

In [129]:
df = df[["alcohol", "malic_acid", "color_intensity", "target"]]
df.tail()

     alcohol  malic_acid  color_intensity  target
173    13.71        5.65              7.7       2
174    13.40        3.91              7.3       2
175    13.27        4.28             10.2       2
176    13.17        2.59              9.3       2
177    14.13        4.10              9.2       2

In [124]:
from sklearn.model_selection import train_test_split

X = df[["alcohol", "malic_acid", "color_intensity"]]
y = df["target"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [125]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(
    criterion="entropy",
    max_depth=4,
    random_state=42
)

model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!

In [126]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.7962962962962963

In [127]:
sample = pd.DataFrame({
    "alcohol": [13.5],
    "malic_acid": [2.0],
    "color_intensity": [5.0]
})

print("Prediction:", model.predict(sample)[0])

Prediction: 0

In [128]:
import joblib
joblib.dump(model, "model.pkl")

print("Model saved as model.pkl")

Model saved as model.pkl